# Generated by Django 4.2.1 on 2023-05-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='img',
            field=models.ImageField(default='default_profile_img.jpg', upload_to='media_local/'),
        ),
    ]
