# Generated by Django 4.2.1 on 2023-08-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_talk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(default='media_local/default_profile_img.jpg', upload_to='media_local/'),
        ),
    ]
